### ISSUE TITLE
Next step: GitHub Acitons CI/CD?

### ISSUE THREAD

**Issue by webknjaz** [tox-dev/azure-pipelines-template#2]

**Comment by gaborbernat** [comment]
The actions go under https://github.com/tox-dev/gh-action-tox

<blockquote><img src="https://repository-images.githubusercontent.com/184619634/05a75200-6cdb-11e9-88e9-d437f0ebd9e7" width="48" align="right"><div><img src="https://github.githubassets.com/favicon.ico" height="14"> GitHub</div><div><strong><a href="https://github.com/tox-dev/gh-action-tox">tox-dev/gh-action-tox</a></strong></div><div>Run tox as a Github Action. Contribute to tox-dev/gh-action-tox development by creating an account on GitHub.</div></blockquote>
