### ISSUE TITLE
Python 3.9 support

### ISSUE THREAD

**Issue by laike9m** [tox-dev/azure-pipelines-template#8]
It seems azure pipeline has added support for Python 3.9 (not 100% sure), so opening an issue here as well.

https://github.com/actions/virtual-environments/issues/1740

**Comment by gaborbernat** [comment]
Addressed with https://github.com/tox-dev/azure-pipelines-template/commit/5618f964105f05885e22edf82e60f2429aa41bd9

**Comment by gaborbernat** [comment]
Well, we added support for it, but seems Azure is still lacking compared to Github Actions:

```
Versions in /opt/hostedtoolcache:

2.7.18 (x64)
3.5.10 (x64)
3.6.12 (x64)
3.7.9 (x64)
3.8.6 (x64)
If this is a Microsoft-hosted agent, check that this image supports side-by-side versions of Python at https://aka.ms/hosted-agent-software
```

**Comment by laike9m** [comment]
That's too bad...but thanks for the quick response

**Comment by laike9m** [comment]
Can we reopen this? According to [this](https://github.com/actions/virtual-environments/blob/releases/win19/20201021/images/win/Windows2019-Readme.md#python) and [this](https://github.com/actions/virtual-environments/blob/releases/macOS-11.0/20201024/images/macos/macos-11.0-Readme.md#python), Python 3.9 should already be supported on Windows and Mac.

**Comment by gaborbernat** [comment]
Addressed https://github.com/tox-dev/azure-pipelines-template/commit/30f07f8d24f708e3e0837ec4d0796666822e76a6
